In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import os

In [11]:
os.chdir("c:\\Users\\User\\Desktop\\Biochem") 
df1 = 'c:\\Users\\User\\Desktop\\Biochem\\merged_datasets.xlsx'

In [ ]:
os.listdir()

In [7]:
df = pd.read_excel('c:\\Users\\User\\Desktop\\Biochem\\merged_datasets.xlsx')

In [9]:
df

,Accession,F21,F22,F23,F24,F25,F26,F27,F28,F29,...,BENIGN_3,BENIGN_5,BENIGN_7,BENIGN_8,MALIGNANT_2,MALIGNANT_4,MALIGNANT_5,MALIGNANT_6,MALIGNANT_7,MALIGNANT_8
0,A0A024QZX5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A0A024R571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A0A075B6H2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A0A075B6H9,NaN,NaN,NaN,NaN,2997772.0,NaN,18729352.0,NaN,5109771.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A0A075B6I0,298754096.0,51723857.0,56849876.0,338939916.0,62999056.0,9235352.0,625791865.8,161510096.0,8628226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3867,X6R5C5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3868,X6R8F3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3869,X6RBG4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3870,X6RFL8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3871,X6RKN2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_healthy = pd.read_excel(df1, sheet_name='health')
df_disease = pd.read_excel(df1, sheet_name='disease')

In [13]:
df_healthy
#df_disease

,Accession,F31,F32,F33,F34,F35,F36,F37,F38,F39,...,HC_M241,HC_M243,HC_M251,HC_M260,HC_M266,HC_M267,HC_M273,HC_M274,HC_M275,HC_M276
0,A0A0A0MS15,7.840356e+07,2.473309e+06,6.397147e+06,6.327926e+05,7.273816e+07,3.546246e+06,5.578734e+07,9.869632e+07,3.159586e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A0A0C4DH72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,18.549697,NaN,NaN,NaN,NaN,18.292007,NaN,17.280765
2,O75882,6.790731e+09,3.040750e+09,2.262326e+09,1.209261e+09,3.637394e+09,1.029462e+09,3.528236e+09,5.225220e+09,4.694125e+09,...,23.456719,23.471627,23.492225,23.555844,23.326009,23.542025,23.410479,23.638817,23.581984,23.578998
3,P00338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,16.584848,NaN,NaN,NaN,NaN,18.630944
4,P01019,4.990597e+10,2.896895e+10,5.164425e+10,2.095375e+10,5.584869e+10,3.613505e+10,3.328421e+10,3.818920e+10,2.799497e+10,...,27.152925,27.139374,27.167555,26.458699,27.089035,26.945569,27.016291,26.856927,26.973938,26.382929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3867,X6R5C5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3868,X6R8F3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3869,X6RBG4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3870,X6RFL8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3871,X6RKN2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
print(df.columns)

Index(['Accession', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28',
       'F29',
       ...
       'BENIGN_3', 'BENIGN_5', 'BENIGN_7', 'BENIGN_8', 'MALIGNANT_2',
       'MALIGNANT_4', 'MALIGNANT_5', 'MALIGNANT_6', 'MALIGNANT_7',
       'MALIGNANT_8'],
      dtype='object', length=185)

In [19]:
column_names = df.columns.tolist()
print(column_names)

 ['Accession', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F42', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'HPwt1', 'HPwt1.1', 'HPwt2', 'HPwt2.1', 'HPwt3', 'HPwt3.1', 'HPwt4', 'HPwt4.1', 'HPwt5', 'HPwt5.1', 'HPwt6', 'HPwt6.1', 'HPwt7', 'HPwt7.1', 'HPwt8', 'HPwt8.1', 'HPwt9', 'HPwt9.1', 'HPwt10', 'HPwt10.1', 'HPvar1', 'HPvar1.1', 'HPvar2', 'HPvar2.1', 'HPvar3', 'HPvar3.1', 'HPvar4', 'HPvar4.1', 'HPvar5', 'HPvar5.1', 'HPvar6', 'HPvar6.1', 'HPvar7', 'HPvar7.1', 'HPvar8', 'HPvar8.1', 'HPvar9', 'HPvar9.1', 'HPvar10', 'HPvar10.1', 'OCwt1', 'OCwt1.1', 'OCwt2', 'OCwt2.1', 'OCwt3', 'OCwt3.1', 'OCwt4', 'OCwt4.1', 'OCwt5', 'OCwt5.1', 'OCwt6', 'OCwt6.1', 'OCwt7', 'OCwt7.1', 'OCwt8', 'OCwt8.1', 'OCwt9', 'OCwt9.1', 'OCwt10', 'OCwt10.1', 'OCvar1', 'OCvar1.1', 'OCvar2', 'OCvar2.1', 'OCvar3', 'OCvar3.1', 'OCvar4', 'OCvar4.1', 'OCvar5', 'OCvar5.1', 'OCvar6', 'OCvar6.1', 'OCvar7', 'OCvar7.1', 'OCvar8', 'OCvar8.1', 'OCvar9', 'OCvar9.1', 'OCvar10', 'OCvar10.1', 'HC_M195', 'HC_M197', 'HC_M198', 'HC_M203', 'HC_M207', 'HC_M208', 'HC_M214', 'HC_M215', 'HC_M216', 'HC_M225', 'HC_M228', 'HC_M230', 'HC_M232', 'HC_M234', 'HC_M241', 'HC_M243', 'HC_M251', 'HC_M260', 'HC_M266', 'HC_M267', 'HC_M273', 'HC_M274', 'HC_M275', 'HC_M276', 'HGSOC_SC02', 'HGSOC_SC30', 'HGSOC_SC33', 'HGSOC_SA06', 'HGSOC_SC01', 'HGSOC_SC24', 'HGSOC_SA01', 'HGSOC_SA02', 'HGSOC_SA04', 'HGSOC_SA05', 'HGSOC_SA09', 'HGSOC_SA10', 'HGSOC_SA11', 'HGSOC_SA15', 'HGSOC_SA16', 'HGSOC_SC04', 'HGSOC_SC06', 'HGSOC_SC08', 'HGSOC_SC10', 'HGSOC_SC15', 'HGSOC_SC16', 'HGSOC_SC17', 'HGSOC_SC22', 'HGSOC_SC27', 'HGSOC_SC28', 'HGSOC_SC34', 'iBAQ G.P 1', 'iBAQ G.P 2', 'iBAQ G.P 3', 'iBAQ G.P 4', 'iBAQ G.P 5', 'iBAQ G.P 6', 'iBAQ G.P 7', 'iBAQ G.P 8', 'iBAQ G.P 9', 'iBAQ G.P 10', 'iBAQ P.P 1', 'iBAQ P.P 2', 'iBAQ P.P 3', 'iBAQ P.P 4', 'iBAQ P.P 5', 'iBAQ P.P 6', 'iBAQ P.P 7', 'iBAQ P.P 8', 'iBAQ P.P 9', 'iBAQ P.P 10', 'BENIGN_1', 'BENIGN_2', 'BENIGN_3', 'BENIGN_5', 'BENIGN_7', 'BENIGN_8', 'MALIGNANT_2', 'MALIGNANT_4', 'MALIGNANT_5', 'MALIGNANT_6', 'MALIGNANT_7', 'MALIGNANT_8']

In [20]:
np.nan

nan

In [23]:
df_healthy.isna()

,Accession,F31,F32,F33,F34,F35,F36,F37,F38,F39,...,HC_M241,HC_M243,HC_M251,HC_M260,HC_M266,HC_M267,HC_M273,HC_M274,HC_M275,HC_M276
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,True,True,True,True,True,True,True,True,True,...,True,True,False,True,True,True,True,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3867,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3868,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3869,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3870,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3871,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [31]:
colname = df_healthy.columns.tolist()
print(colname)

['Accession', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'HPwt1', 'HPwt1.1', 'HPwt2', 'HPwt2.1', 'HPwt3', 'HPwt3.1', 'HPwt4', 'HPwt4.1', 'HPwt5', 'HPwt5.1', 'HPwt6', 'HPwt6.1', 'HPwt7', 'HPwt7.1', 'HPwt8', 'HPwt8.1', 'HPwt9', 'HPwt9.1', 'HPwt10', 'HPwt10.1', 'HPvar1', 'HPvar1.1', 'HPvar2', 'HPvar2.1', 'HPvar3', 'HPvar3.1', 'HPvar4', 'HPvar4.1', 'HPvar5', 'HPvar5.1', 'HPvar6', 'HPvar6.1', 'HPvar7', 'HPvar7.1', 'HPvar8', 'HPvar8.1', 'HPvar9', 'HPvar9.1', 'HPvar10', 'HPvar10.1', 'HC_M195', 'HC_M197', 'HC_M198', 'HC_M203', 'HC_M207', 'HC_M208', 'HC_M214', 'HC_M215', 'HC_M216', 'HC_M225', 'HC_M228', 'HC_M230', 'HC_M232', 'HC_M234', 'HC_M241', 'HC_M243', 'HC_M251', 'HC_M260', 'HC_M266', 'HC_M267', 'HC_M273', 'HC_M274', 'HC_M275', 'HC_M276']

In [27]:
df_healthy.isna().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of       Accession    F31    F32    F33    F34    F35    F36    F37    F38  \
0         False  False  False  False  False  False  False  False  False
1         False   True   True   True   True   True   True   True   True
2         False  False  False  False  False  False  False  False  False
3         False   True   True   True   True   True   True   True   True
4         False  False  False  False  False  False  False  False  False
...         ...    ...    ...    ...    ...    ...    ...    ...    ...
3867      False   True   True   True   True   True   True   True   True
3868      False   True   True   True   True   True   True   True   True
3869      False   True   True   True   True   True   True   True   True
3870      False   True   True   True   True   True   True   True   True
3871      False   True   True   True   True   True   True   True   True

        F39  ...  HC_M241  HC_M243  HC_M251  HC_M260  HC_M266  HC_M267  \
0     False  ...     True     True     True     True     True     True
1      True  ...     True     True    False     True     True     True
2     False  ...    False    False    False    False    False    False
3      True  ...     True     True     True     True    False     True
4     False  ...    False    False    False    False    False    False
...     ...  ...      ...      ...      ...      ...      ...      ...
3867   True  ...     True     True     True     True     True     True
3868   True  ...     True     True     True     True     True     True
3869   True  ...     True     True     True     True     True     True
3870   True  ...     True     True     True     True     True     True
3871   True  ...     True     True     True     True     True     True

      HC_M273  HC_M274  HC_M275  HC_M276
0        True     True     True     True
1        True    False     True    False
2       False    False    False    False
3        True     True     True    False
4       False    False    False    False
...       ...      ...      ...      ...
3867     True     True     True     True
3868     True     True     True     True
3869     True     True     True     True
3870     True     True     True     True
3871     True     True     True     True

[3872 rows x 76 columns]>

In [ ]:
'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F42', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41'

In [33]:
column_names = [ 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37',
                 'F38', 'F39', 'F40', 'F41', 'HPwt1', 'HPwt1.1', 'HPwt2', 'HPwt2.1',
                   'HPwt3', 'HPwt3.1', 'HPwt4', 'HPwt4.1', 'HPwt5', 'HPwt5.1', 'HPwt6', 'HPwt6.1', 'HPwt7', 'HPwt7.1', 'HPwt8', 'HPwt8.1', 'HPwt9', 'HPwt9.1', 'HPwt10', 'HPwt10.1', 'HPvar1', 'HPvar1.1', 'HPvar2',
                     'HPvar2.1', 'HPvar3', 'HPvar3.1', 'HPvar4', 'HPvar4.1', 'HPvar5', 'HPvar5.1', 'HPvar6', 'HPvar6.1', 'HPvar7', 'HPvar7.1', 'HPvar8', 'HPvar8.1', 'HPvar9', 'HPvar9.1', 'HPvar10', 'HPvar10.1',
                       'HC_M195', 'HC_M197', 'HC_M198', 'HC_M203', 'HC_M207', 'HC_M208', 'HC_M214', 'HC_M215', 'HC_M216', 'HC_M225', 'HC_M228', 'HC_M230', 'HC_M232', 'HC_M234', 'HC_M241', 'HC_M243', 'HC_M251',
                 'HC_M260', 'HC_M266', 'HC_M267', 'HC_M273', 'HC_M274', 'HC_M275', 'HC_M276']
mean_val = df_healthy[column_names].mean()
print(mean_val)

F31        5.785423e+09
F32        2.644704e+09
F33        3.712670e+09
F34        1.775628e+09
F35        4.290937e+09
               ...
HC_M267    1.933931e+01
HC_M273    1.934268e+01
HC_M274    1.933524e+01
HC_M275    1.933833e+01
HC_M276    1.934446e+01
Length: 75, dtype: float64

In [34]:
empty_cells_count = df_healthy.isnull().sum()
print(empty_cells_count)

Accession       0
F31          2792
F32          2822
F33          2851
F34          2899
             ...
HC_M267      3219
HC_M273      3200
HC_M274      3169
HC_M275      3212
HC_M276      3245
Length: 76, dtype: int64